src/project/routes/admin.py
"""Admin routes."""

from flask import Blueprint, render_template, request
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, EmailField
from wtforms.validators import DataRequired, Length
from src.project.services import auth_service

admin_bp = Blueprint("admin", __name__)


class LoginForm(FlaskForm):
    """
    Login form.

    Attributes:
        email (StringField): Email field.
        password (PasswordField): Password field.
    """

    email = EmailField(
        "Email",
        validators=[DataRequired()],
        render_kw={"placeholder": "Email address", "class": "input is-primary"},
    )
    password = PasswordField(
        "Password",
        validators=[DataRequired(), Length(min=8)],
        render_kw={"placeholder": "Password", "class": "input is-primary"},
    )


class SignupForm(FlaskForm):
    """
    Signup form.

    Attributes:
        name (StringField): Name field.
        email (StringField): Email field.
        password (PasswordField): Password field.
        confirm_password (PasswordField): Confirm password field.
        agree_terms (BooleanField): Agree terms field.
    """

    name = StringField(
        "Name",
        validators=[DataRequired()],
        description="Enter your name",
        render_kw={"placeholder": "Name", "class": "input is-primary"},
    )
    email = StringField(
        "Email",
        validators=[DataRequired()],
        description="Enter your email address",
        render_kw={"placeholder": "Email address", "class": "input is-primary"},
    )
    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
        ],
        description="Enter your password",
        render_kw={"placeholder": "Password", "class": "input is-primary"},
    )
    confirm_password = PasswordField(
        "Confirm Password",
        validators=[DataRequired()],
        description="Confirm your password",
        render_kw={"placeholder": "Confirm password", "class": "input is-primary"},
    )
    agree_terms = BooleanField("I accept the Terms and Conditions", validators=[DataRequired()])


class ResetPasswordForm(FlaskForm):
    """
    Reset password form.

    Attributes:
        email (StringField): Email field.
    """

    email = EmailField(
        "Email",
        validators=[DataRequired()],
        render_kw={"placeholder": "Email address", "class": "input is-primary"},
    )


@admin_bp.route("/login", methods=["GET", "POST"])
def login_form():
    """
    Get login form.

    Returns:
        str: Rendered template.
    """
    form = LoginForm()

    if request.method == "POST" and form.validate():
        return "Form submitted successfully!"

    # form.email.errors = ["Invalid email or password"]
    # form.password.errors = ["Invalid email or password"]

    return render_template("login.jinja", form=form)


@admin_bp.route("/signup", methods=["GET", "POST"])
def signup_form():
    """
    Get signup form.

    Returns:
        str: Rendered template.
    """
    form = SignupForm()

    if request.method == "POST" and form.validate():
        return "Form submitted successfully!"

    return render_template("signup.jinja", form=form)


@admin_bp.route("/reset-password", methods=["GET", "POST"])
def reset_password_form():
    """
    Get reset password form.

    Returns:
        str: Rendered template.
    """
    form = ResetPasswordForm()

    if request.method == "POST" and form.validate():
        return "Form submitted successfully!"

    return render_template("reset_password.jinja", form=form)


@admin_bp.get("/terms")
def terms():
    return render_template("terms.jinja")

src/project/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Rest API" />
        <meta name="keywords"
              content="Rest API, Flask, Python, SQLAlchemy, Marshmallow, JWT, Docker, Docker Compose, PostgreSQL, Redis"/>
        <meta name="author" content="Juan Rabadan" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
</head>
        {% block styles %}
        {% endblock styles %}
    </head>
    <body>
        {% block content %}
        {% endblock content %}
        <script src="https://unpkg.com/htmx.org@1.8.6"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

src/project/templates/index.jinja
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Rest API" />
        <meta name="keywords"
              content="Rest API, Flask, Python, SQLAlchemy, Marshmallow, JWT, Docker, Docker Compose, PostgreSQL, Redis"/>
        <meta name="author" content="Juan Rabadan" />
        <title>Bulma</title>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.min.css"/>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
        {# <link rel="stylesheet" href="/static/css/debug.css" /> #}
    </head>
    <body>
        <nav class="navbar has-shadow is-white">
            <!-- Logo brand -->
            <div class="navbar-brand">
                <a href="#" class="navbar-item">
                    <img src="/static/img/logo.png" style="max-height:70px;" class="py-2 px-2" />
                </a>
                <a class="navbar-burger" id="burger">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </div>
            <div class="navbar-menu" id="nav-links">
                <div class="navbar-end">
                    <a class="navbar-item">My Account</a>
                    <a class="navbar-item">Settings</a>
                </div>
            </div>
        </nav>
        <!-- Breadcumbs -->
        <div class="section pt-4 pb-0">
            <nav class="breadcrumb has-arrow-separator">
                <ul class="container">
                    <li>
                        <a class="has-text-grey">Cofee Ninja</a>
                    </li>
                    <li>
                        <a class="has-text-grey">Shop</a>
                    </li>
                    <li class="is-active">
                        <a href="">Docker Dark Roast</a>
                    </li>
                </ul>
            </nav>
        </div>
        <!-- Product -->
        <section class="section">
            <div class="container">
                <div class="columns is-vcentered is-multiline">
                    <div class="column is-6-tablet is-3-desktop">
                        <h1 class="is-size-3-mobile is-size-1-desktop title">Docker</h1>
                        <h2 class="is-size-3-mobile is-size-2-desktop subtitle">Dark Roast</h2>
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque accusantium autem odit tempore enim inventore consequatur ut voluptatum explicabo! Autem impedit culpa assumenda blanditiis explicabo voluptas consectetur reprehenderit inventore deleniti.
                        </p>
                    </div>
                    <div class="column is-6-tablet is-5-desktop has-text-centered">
                        <!-- Add image dummy from internet -->
                        <img src="/static/img/coffee2.jpg" alt="Docker Dark Roast" class="px-6"/>
                    </div>
                    <div class="column is-12-tablet is-4-desktop">
                        <div class="is-size-4 mb-4">$10.95</div>
                        <p class="mb-4">
                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Distinctio excepturi possimus cupiditate cum culpa est pariatur provident? Delectus voluptatem, culpa placeat, incidunt reprehenderit facere!
                        </p>
                        <form>
                            <div class="control mb-6">
                                <div class="select is-dark">
                                    <select>
                                        <option>
                                            Small (250s)
                                        </option>
                                        <option>
                                            Larger (500g)
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <button class="button is-primary">Add to Cart</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <section class="section">
            <div class="container">
                <div class="columns is-8 is-variable">
                    <div class="column is-7-tablet">
                        <!-- tabbed content -->
                        <div class="tabs is-boxed">
                            <ul>
                                <li class="is-active" data-target="product-details">
                                    <a>Product Details</a>
                                </li>
                                <li data-target="delivery-information">
                                    <a>Delivery Information</a>
                                </li>
                            </ul>
                        </div>
                        <div class="px-2" id="tab-content">
                            <div id="product-details">
                                <h3 class="is-size-5 titlte">Product Details</h3>
                                <p>
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, eligendi aliquid molestias voluptates perferendis ad nisi dolore corrupti aut accusamus cupiditate quam a laudantium minima delectus praesentium nulla recusandae est.
                                    Voluptates facilis alias sed recusandae assumenda, explicabo dolorum incidunt tenetur doloribus, maiores minus repudiandae totam voluptatum corrupti! Ducimus eligendi quas assumenda rerum autem, suscipit repudiandae ut molestias? Velit, nemo praesentium!
                                </p>
                            </div>
                            <div id="delivery-information" class="is-hidden">
                                <h3 class="is-size-5 titlte">Delivery Information</h3>
                                <p>
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, eligendi aliquid molestias voluptates perferendis ad nisi dolore corrupti aut accusamus cupiditate quam a laudantium minima delectus praesentium nulla recusandae est.
                                    Voluptates facilis alias sed recusandae assumenda, explicabo dolorum incidunt tenetur doloribus, maiores minus repudiandae totam voluptatum corrupti! Ducimus eligendi quas assumenda rerum autem, suscipit repudiandae ut molestias? Velit, nemo praesentium!
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="column is-5-tablet">
                        <div class="message is-dark">
                            <div class="message-header">
                                <p>Earns Points with the Cofee Club</p>
                            </div>
                            <div class="message-body">
                                <p>
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, nostrum unde repellat culpa iusto dolorem, illo laborum placeat quidem consectetur incidunt eos officia reiciendis fugit necessitatibus nobis itaque? Hic, quasi.
                                    Recusandae facilis at dicta illo expedita vero nesciunt porro quaerat enim.
                                </p>
                                <div class="has-text-centered">
                                    <button class="button" id="signup">Signup</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Cards -->
        <section class="section is-hidden-mobile">
            <div class="container">
                <h3 class="title has-text-centered is-size-4">Related Products</h3>
                <div class="columns mt-5 is-8 is-variable is-centered">
                    <div class="column is-4-tablet is-3 desktop">
                        <div class="card">
                            <div class="card-image has-text-centered px-6">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="">
                            </div>
                            <div class="card-content">
                                <p>$12.95</p>
                                <p class="title is-size-5">Cortado Cup</p>
                            </div>
                            <footer class="card-footer">
                                <p class="card-footer-item">
                                    <a class="has-text-grey">View</a>
                                </p>
                            </footer>
                        </div>
                    </div>
                    <div class="column is-4-tablet is-3 desktop">
                        <div class="card">
                            <div class="card-image has-text-centered px-6">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="">
                            </div>
                            <div class="card-content">
                                <p>$12.95</p>
                                <p class="title is-size-5">
                                    Cortado Cup
                                </p>
                            </div>
                            <footer class="card-footer">
                                <p class="card-footer-item">
                                    <a class="has-text-grey">View</a>
                                </p>
                            </footer>
                        </div>
                    </div>
                    <div class="column is-4-tablet is-3 desktop">
                        <div class="card">
                            <div class="card-image has-text-centered px-6">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="">
                            </div>
                            <div class="card-content">
                                <p>
                                    $12.95
                                </p>
                                <p class="title is-size-5">
                                    Cortado Cup
                                </p>
                            </div>
                            <footer class="card-footer">
                                <p class="card-footer-item">
                                    <a class="has-text-grey">View</a>
                                </p>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Modal -->
        <div class="modal">
            <div class="modal-background">
            </div>
            <div class="modal-content has-background-white py-5 px-5">
                <h3 class="title mb-6">
                    Join the Club
                </h3>
                <form>
                    <div class="field">
                        <label class="label">
                            name
                        </label>
                        <div class="control">
                            <input class="input" type="text" placeholder="Name" />
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">
                            email
                        </label>
                        <div class="control">
                            <input class="input" type="text" placeholder="Email" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <label for="" class="checkbox">
                                <input type="checkbox" />
                                I agree to the <a href="#">terms and conditions</a>
                            </label>
                        </div>
                    </div>
                    <div class="mt-6 has-text-centered">
                        <button class="button is-warning">
                            Submit
                        </button>
                    </div>
                </form>
            </div>
        </div>


        <!-- Footer -->
        <footer class="footer">
            <div class="content has-text-centered">
                <p>Copyright 2023 Coffee Ninja</p>
            </div>
        </footer>

        <script type="text/javascript" src="/static/js/index.js"></script>
    </body>
</html>

src/project/templates/login.jinja
{% extends "base.jinja" %}
{% from "helpers/form.jinja" import render_login_field, render_email_field, render_password_field %}
{% block title %}
    Login
{% endblock title %}
{% block content %}
    <div class="hero is-fullheight">
        <div class="hero-body is-justify-content-center is-align-items-center">
            <div class="columns is-flex is-flex-direction-column">
                <div class="column field has-text-centered">
                    <img src="{{ url_for('static', filename='img/logo.png') }}"
                         width="100"
                         alt="Company Logo"/>
                </div>
                <div class="columns is-flex is-flex-direction-column box">
                    <h1 class="title has-text-centered">Login</h1>
                    <div class="column">
                        <form method="post" action="{{ url_for('admin.login_form') }}">
                            {{ form.csrf_token }}
                            {{ render_email_field(form.email) }}
                            {{ render_password_field(form.password) }}
                            <div class="field has-text-right">
                                <a href="{{ url_for('admin.reset_password_form') }}"
                                   class="has-text-primary">forget password?</a>
                            </div>
                            <div class="field">
                                <button class="button is-primary is-fullwidth" type="submit">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="has-text-centered">
                    <p>
                        Don't have an account? <a href="{{ url_for('admin.signup_form') }}" class="has-text-primary">Sign up</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/project/templates/reset_password.jinja
    {% extends "base.jinja" %}
    {% from "helpers/form.jinja" import render_login_field, render_email_field, render_password_field %}
    {% block title %}
        Login
    {% endblock title %}
    {% block content %}
        <div class="hero is-fullheight">
            <div class="hero-body is-justify-content-center is-align-items-center">
                <div class="columns is-flex is-flex-direction-column">
                    <div class="column field has-text-centered">
                        <img src="{{ url_for('static', filename='img/logo.png') }}"
                        width="100"
                        alt="Company Logo"/>
                    </div>
                    <div class="columns is-flex is-flex-direction-column box">
                        <h1 class="title has-text-centered">Reset password</h1>
                        <div class="column">
                            <form method="post" action="{{ url_for('admin.login_form') }}">
                                {{ form.csrf_token }}
                                {{ render_email_field(form.email) }}
                                <div class="field">
                                    <button class="button is-primary is-fullwidth" type="submit">Reset password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="has-text-centered">
                        <p>
                            Do you have an account? <a href="{{ url_for('admin.login_form') }}" class="has-text-primary">Login</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}

src/project/templates/signup.jinja
{% extends "base.jinja" %}
{% from "helpers/form.jinja" import render_user_field, render_email_field, render_password_field, render_agree_terms_field %}
{% block title %}
    Signup
{% endblock title %}
{% block content %}
    <div class="hero is-fullheight">
        <div class="hero-body is-justify-content-center is-align-items-center">
            <div class="columns is-flex is-flex-direction-column">
                <div class="column field has-text-centered">
                    <img src="{{ url_for('static', filename='img/logo.png') }}"
                         width="100"
                         alt="Company Logo"/>
                </div>
                <div class="columns is-flex is-flex-direction-column box">
                    <h1 class="title">Signup</h1>
                    <form method="post" action="{{ url_for('admin.signup_form') }}">
                        {{ form.csrf_token }}
                        {{ render_user_field(form.name) }}
                        {{ render_email_field(form.email) }}
                        {{ render_password_field(form.password) }}
                        {{ render_password_field(form.confirm_password) }}
                        {{ render_agree_terms_field(form.agree_terms) }}

                        <div class="column">
                            <button class="button is-primary is-fullwidth" type="submit">Create an account</button>
                        </div>
                    </form>
                </div>
                <div class="has-text-centered">
                    <p>
                        Already have an account?  <a href="{{ url_for('admin.login_form') }}" class="has-text-primary">Login</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/project/templates/users copy.html
<html>
    <head>
        <title>Users</title>
        {# <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css"
       rel="stylesheet"/> #}
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.min.css"/>
        <style>
            body {
                font-family: Sans-Serif;
            }
            input.gridjs-search-input {
                width: 50%;
                padding: 0.5rem;
                border: 1px solid #dbdbdb;
                border-radius: 4px;
                box-shadow: none;
                box-sizing: border-box;
                font-size: 13px;
            }

        </style>
        <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
    </head>
    <body>
        <div>
            <div class="container">
                <div class="hero-body">
                    <h1 class="title">Users</h1>
                    <div id="table" class="table-container"></div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            const tableDiv = document.getElementById('table');

            const table = new gridjs.Grid({
                sort: {
                    multiColumn: false,
                    enabled: false,
                    server: {
                        url: (prev, columns) => {
                                if (!columns.length) return prev;
                                const col = columns[0];
                                const dir = col.direction === 1 ? '+' : '-';
                                let colName = ["id","first_name", "last_name", "email"][col.index];
                                const sort = dir + colName;
                                return `${prev}${(prev.indexOf('?') >= 0 ? '&' : '?')}sort=${dir}${colName}`
                            },
                        },
                },
                columns: [
                        { id: 'id', 'hidden': true },
                        { id: 'first_name', name: 'First Name', sort: false},
                        { id: 'last_name', name: 'Last Name', sort: false },
                        { id: 'email', name: 'Email', sort: false },
                ],
                search: {
                    enabled: true,
                    server: {
                        url: (prev, search) => {
                            return prev + (prev.indexOf('?') >= 0 ? '&' : '?') + new URLSearchParams({search}).toString();
                    },
                },
                },

                    pagination: {
                        enabled: true,
                        limit: 3,
                        server: {
                            url: (prev, page, limit) => {
                                return prev + (prev.indexOf('?') >= 0 ? '&' : '?') + new URLSearchParams({start: page * limit, length: limit}).toString();
                            },
                            total: (result) => {
                                return result.total;
                            }
                        },
                    },
                    server: {
                    url: '/api/users',
                    then: results => results.data.map(user => [user.id, user.first_name,  user.last_name, user.email]),
                    total: results => results.total,
                },
                className: {
                    table: 'table is-bordered is-hoverable',
                    footer: 'p-4',
                    pagination: 'pagination',
                    paginationButtonNext: 'pagination-next',
                    paginationButtonPrev: 'pagination-previous',
                    paginationButtonCurrent: 'pagination-link is-current',
                    paginationButton: 'pagination-link',
                    search: 'p-4',
                }
                });

            table.render(tableDiv);

        </script>
    </body>
</html>

src/project/templates/users.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta name="description"
              content="A simple CRUD app using Flask and SQLAlchemy"/>
        <meta name="keywords" content="Flask, SQLAlchemy, CRUD, Python" />
        <title>Users</title>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.min.css"/>
        <link rel="stylesheet"
              href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css"/>
    </head>
    <body>
        <section class="section">
            <div class="container">
                <h1 class="title">Users</h1>
                <div class="columns">
                    <div class="column is-12">
                        <div id="grid"></div>
                    </div>
                </div>
            </div>
        </section>
        <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
        <script>
            const updateUrl = (prev, query) => {
                return prev + (prev.indexOf('?') >= 0 ? '&' : '?') + new URLSearchParams(query).toString();
            };

      const grid = new gridjs.Grid({
        columns: [
          "Id",
          "First Name",
          "Last Name",
          { id: 'email', name: 'Email', sort: false, formatter: (cell, row) => {
            return gridjs.html('<a href="mailto:' + cell + '">' + cell + '</a>');
          }},
          {
            name: "Actions",
            formatter: (_, row) =>
              gridjs.html(
                `<button class="button is-small is-danger" data-row-id="${ row.cells[0].data }">Delete</button>`
              ),
            sort: false
          },
        ],
        server: {
          url: "/api/users",
          then: (res) =>
            res.data.map((user) => [
              user.id,
              user.first_name,
              user.last_name,
              user.email,
              null, // We use null here to add the delete button column
            ]),
          total: (res) => res.total,
        },
        search: {
          server: {
            url: (prev, search) => updateUrl(prev, {search}),
          },
        },
        pagination: {
          limit: 3,
          server: {
            url: (prev, page, limit) => updateUrl(prev, {start: page * limit, length: limit}),
            totalPages: (res) => Math.ceil(res.total / res.per_page),
          },
        },
        sort: {
          multiColumn: true,
          server: {
            url: (prev, columns) => {
              if (!columns.length) return prev;
              const col = columns[0];
              const dir = col.direction === 1 ? "+" : "-";
              const colName =
                col.id === 0 ? "id" : col.id === 1 ? "first_name" : "last_name";
              const sort = `${dir}${colName}`;
              return updateUrl(prev, {sort});
            },
          },
        },
      });

      grid.render(document.getElementById("grid"));
        </script>
    </body>
</html>